version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nodejs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jpgmzrhp9ffr"
s3_prefix = "nodejs"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
